version: "3.9"
services:
  rmq:
    image: rabbitmq:management
    container_name: rmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 3s
      retries: 10

  bot:
    build: dbot
    container_name: dbot
    depends_on:
      rmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rmq
    env_file:
      - .env

  worker:
    build: worker
    depends_on:
      rmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rmq
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure