version: "3.9"
services:
  rmq:
    build: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    env_file:
      - .env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 3s
      retries: 10

  bot:
    build: dbot
    container_name: dbot
    environment:
      - RABBITMQ_HOST=rmq
    env_file:
      - .env
    depends_on:
      rmq:
        condition: service_healthy

  worker:
    build: worker
    environment:
      - RABBITMQ_HOST=rmq
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      rmq:
        condition: service_healthy
